name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "https://lapras.com/public/ROSXTKN"
          # 以下オプション
          # https://lapras-card-generator.vercel.app でカスタマイズしたデザインを設定可能
          ICON_FIRST: "#007B5C"
          ICON_SECOND: "#00BF8F"
          BACKGROUND_FIRST: "#004736"
          BACKGROUND_SECOND: "#00BF8F"
          LANG: "en"
          CARD_WIDTH: "350"
          # UPDATE_TIME: "true"
          # README_FILE: "README.md"
          # IS_CENTER: "true"
          # ALTERNATIVE_TEXT: "Score of {SHARE_ID} on LAPRAS"
